print("---- arithmetic and variable ----");
set $number - -12+24*(53-6)-7;
print("number: ", $number, ", expected 1133");

print("---- if ----");
if (1) {
    print("1. Ok");
} else {
    print("1. Failed");
}

if (0) {
    print("2. Failed");
} else {
    print("2. Ok");
}

print("---- if-goto cycle ----");
set $i 0;
@l: set $i $i+1;
    print("i: ", $i);
    if ($i < 10)
        goto @l;

print("---- while ----");
set $i 0;
while ($i < 10) {
    set $i $i+1;
    print("i: ", $i);
}
